Crown-Commercial-Service/conclave-ssso-ui

src/app/pages/manage-group/manage-group-view/manage-group-view-component.html, src/app/pages/manage-organisation/manage-organisation-registration-step-1/manage-organisation-registration-step-1.component.html, src/app/pages/manage-organisation/manage-reg-organisation-search/manage-reg-organisation-search.component.html, src/app/pages/manage-organisation/manage-reg-organisation-search/manage-reg-organisation-search.component.ts
Also include bug fix for org search
=> Bug fixes in NHS registry and MFA removal in group

src/app/pages/contact-admin/contact-admin.component.ts, src/environments/environment-uat.ts
=> P2sprint6 merge into main

src/app/pages/buyer/details/details.component.ts
As discussed with Ruban, Add fix to show 'Internal Identifier' for 'GB-CCS' type
=> Manage service eligibility fix UI

Auth0Templates/LogIn.html, src/app/pages/manage-organisation/manage-organisation-profile/manage-organisation-profile.component.html, src/app/pages/manage-organisation/manage-organisation-profile/manage-organisation-profile.component.ts, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.html, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/app/services/wrapper/wrapper-configuration.service.ts, src/app/services/wrapper/wrapper-org--group-service.ts, src/assets/i18n/en.json
Changes done for AC upto 5 from ticket - con-2620
=> Feature/con 2620 federated login upto AC4

src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.html, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.scss
•	Angular app
This includes
•	2870-CAS Content - User Accounts Description-changes
=> release note - 20220826-3 (release for test environment)

src/app/app-routing.module.ts, src/app/pages/manage-delegated/delegated-user-confirm/delegated-user-confirm.component.ts, src/app/pages/manage-delegated/delegated-user-list/delegated-user-list.component.html
•	Angular app
This includes
•	3614-UI and functionality issues related to the search bar
•	3613-Issue with giving delegated access to users with the default start date and default end date
=> dev release note - 20220825-4

src/app/app-routing.module.ts, src/app/pages/manage-delegated/delegated-user-confirm/delegated-user-confirm.component.ts, src/app/pages/manage-delegated/delegated-user-list/delegated-user-list.component.html
=> p2sprint12 updated to sandbox

src/app/pages/manage-delegated/delegated-access-user/delegated-access-user.component.ts
Please find the following release notes for Front end.
•	P2spirnt12 branch
•	Angular app
•	Vault changes: NA
•	DB Changes: NA
Pull request: https://github.com/Crown-Commercial-Service/conclave-ssso/pull/862
Pull request UI: https://github.com/Crown-Commercial-Service/conclave-ssso-ui/pull/691
This includes
1.	[Bug 3571](https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/3571): Delegation | obfuscated word can be use as keyword in API search-string
2.	[Bug 3626](https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/3626): Delegation | Get delegated user API issues
3.	[Bug 3625](https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/3625): Delegation | Future access granted users can access to delegated org
Thanks,
=> Edit delegation date populate issue fixed (#691)

src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.html, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.scss, src/app/services/wrapper/wrapper-org--group-service.ts
•	Angular app
This includes
•	3643- Uplift the content changes that were made on add/edit user page to Sprint 12 code-CAS related changes
=> Dev release note - 20220902

src/app/services/wrapper/wrapper-user-delegated.service.ts
api param changes for delegation api access issue
=> Delegation api param changes for access issue

src/app/pages/manage-organisation/manage-organisation-profile/manage-organisation-profile.component.ts, src/app/pages/manage-organisation/manage-organisation-remove-idp-confirm/manage-organisation-remove-idp-confirm.html, src/app/pages/manage-organisation/manage-organisation-remove-idp-confirm/manage-organisation-remove-idp-confirm.ts, src/app/services/wrapper/wrapper-user-delegated.service.ts
Please find the following release notes.
•	P2sprint13 branch
•	API – External
•	App changes: Yes
•	Vault changes: No
•	Database change: Yes
Please deploy it into Dev Environment
Database:
•	Phase2_Sprint13/20220905093800_Add_IdentityProvider_DisplayOrder.sql
Pull Request: 
•	https://github.com/Crown-Commercial-Service/conclave-ssso/pull/886
•	https://github.com/Crown-Commercial-Service/conclave-ssso-ui/pull/704
This includes
[Task 3588](https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/3588): CON-2841-Removing federated sign in option prompt to org admin - Content update-Priority 1
=> Merge from P2sprint13 to Development

src/app/pages/user-profile/user-profile-component.ts
https://crowncommercialservice.atlassian.net/browse/CON-2736
=> Bug 3482: User role not updating bug fix.

src/app/pages/user-profile/user-profile-component.ts
P2spirnt13 branch
Angular app
Vault changes: NA
DB Changes: NA
Please deploy it into DEV Environment
Pull request:  https://github.com/Crown-Commercial-Service/conclave-ssso-ui/pull/712
This includes
[Bug 3482](https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/3482): CCS SIT BUG- Con CON-2736- Search for Organisations is not working for the first time for MSE role
=> Bug 3482: User role not updating bug fix. (#712)

src/app/pages/buyer/details/details.component.ts
[Task 2114](https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/2114): Sprint 14-CON-1453 CCS Admin >Manage Service eligibility >Confirm Organisation page is expected to show all Identifiers- Priority 3- Carry Over
[Task 2116](https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/2116): Sprint 14-CON-1373 User with Manage Service eligibility role cannot access Organisation Identifiers- Same task as Con 1453
=> User with Manage Service eligibility role cannot access Organisation Identifiers

Auth0Templates/LogIn.html, Auth0Templates/Mfa.html, src/index.html
•	Angular app
Auth0-changes
1)Login Page
2)MFA Page
•	
This includes
•	3589-CON-2519-Implement GA4 tags in PPG(Script Update)
=> Dev release note - 20220919 -1

Auth0Templates/LogIn.html, Auth0Templates/Mfa.html, Auth0Templates/ResetPassword.html, src/app/pages/manage-delegated/delegated-access-user/delegated-access-user.component.ts
•	Angular app
This includes
•	[Task 3691](https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/3691): delegation Bugs
=> Dev release note - 20220920 - 1

src/app/logging/rollbar.ts
•	Angular app
This includes
•	[Task 3725](https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/3725): CON-2953-Rollbar API changes required to support environment segregation -Front End Changes(Log changes)
=> Dev release note - 20220923 - 1

src/app/models/user.ts, src/app/pages/contact-admin/contact-admin.component.html, src/app/pages/contact-admin/contact-admin.component.ts, src/app/services/wrapper/wrapper-org--group-service.ts
contact admin page updated to call user api instead of calling admin user
=> PR-2884-Refactoring-of-adminusers-endpoint-FE

src/app/pages/manage-organisation/manage-organisation-registration-add-user/manage-organisation-registration-add-user.component.ts, src/app/pages/manage-organisation/manage-organisation-registration-error-details-wrong/manage-organisation-registration-error-details-wrong.component.ts, src/app/pages/manage-organisation/manage-organisation-registration-error-not-my-organisation/manage-organisation-registration-error-not-my-organisation.component.ts, src/app/pages/manage-organisation/manage-organisation-registration-step-3/manage-organisation-registration-step-3.component.ts, src/app/pages/manage-organisation/manage-reg-organisation-status-duplicate/manage-reg-organisation-status-duplicate.component.ts
Please find the following release notes.
•	P2spirnt15 branch
•	Angular app
This includes
•	[Task 3755](https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/3755): CON-2152-Back Button Loop
=> Dev release note - 20220930 -2

src/app/services/wrapper/wrapper-org--group-service.ts
Query string variable name updated
=> PR-admin-user-refactoring-fix

src/app/pages/manage-delegated/service/manage-delegate.service.ts
patch for sprint 14 about logout issue while switching delegation organisation
=> PR-Fix-for-user-logout-issue-while-switching-org-sprint14

src/app/pages/manage-delegated/service/manage-delegate.service.ts
switching delegation organisation
=> patch for sprint 14 about logout issue while (#782)

src/app/interceptors/loading-indicator.interceptor.ts, src/app/pages/manage-delegated/service/manage-delegate.service.ts, src/app/services/auth/auth.service.ts
•	P2sprint15 branch
•	App changes: Yes
•	Database change: NA
Please deploy it into Dev environment
Pull Request: 
•	https://github.com/Crown-Commercial-Service/conclave-ssso-ui/pull/784
This includes
•	Fix to show loading indicator while switching organization
=> Dev release note-20221006 (sprint 15)

src/app/models/user.ts, src/app/pages/contact-admin/contact-admin.component.ts
Email hyperlink issue fixed with mailto attribute to email client
=> PR-3771-UI-Contact-Admin-UI-bugs

src/app/models/user.ts, src/app/pages/contact-admin/contact-admin.component.ts
Find the following release notes.
•	P2spirnt15 branch
•	Backend(frontend) 
•	No vault/DB changes
Q/A
https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/2884
[@Nishadi Lakshika](mailto:nishadi.lakshika@brickendon.com) This will fix  Hyperlink style and mailto:emailId
=> Re: Dev release note-20221007 (sprint 15)

src/app/interceptors/loading-indicator.interceptor.ts, src/app/pages/manage-delegated/service/manage-delegate.service.ts, src/app/services/auth/auth.service.ts
•	P2sprint14 branch
•	App changes: Yes
•	Database change: NA
Please deploy it into Test environment
Pull Request: 
•	https://github.com/Crown-Commercial-Service/conclave-ssso-ui/pull/792
This includes
•	https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/3773 (Fix to show loading indicator while switching organization)
=> Test release note-20221007 (sprint 14)

src/app/pages/manage-delegated/delegated-access-user/delegated-access-user.component.html, src/app/pages/manage-delegated/delegated-access-user/delegated-access-user.component.scss, src/app/pages/manage-delegated/delegated-access-user/delegated-access-user.component.ts
•	P2spirnt15 branch
•	Angular app
This includes
•	Fix for the issue related to cancel button and the start date field in adding delegation flow
=> disble issue fixed (#802) Dev release note - 20221012-1

Auth0Templates/LogIn.html, src/app/pages/manage-organisation/manage-organisation-profile/manage-organisation-profile.component.html, src/app/services/wrapper/wrapper-configuration.service.ts
•	P2spirnt15 branch
•	Angular app
This includes
•	[Task 3816](https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/3816): Con 3046 - Hide IDp provider buttons from Sign in page
=> Dev release note - 20221014 - 1

src/app/pages/manage-organisation/manage-organisation-profile/manage-organisation-profile.component.html, src/app/pages/manage-organisation/manage-organisation-profile/manage-organisation-profile.component.ts, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.html, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/app/pages/user-profile/user-profile-component.ts, src/app/services/wrapper/wrapper-configuration.service.ts, src/environments/environment.ts
* 3046 issues fixed
* environment changes updated
=> 3046 issues fixed (#836)

src/app/pages/manage-organisation/manage-organisation-profile/manage-organisation-profile.component.html, src/app/pages/manage-organisation/manage-organisation-profile/manage-organisation-profile.component.ts, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.html, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/app/pages/user-profile/user-profile-component.ts, src/app/services/wrapper/wrapper-configuration.service.ts, src/environments/environment.ts
Reverts Crown-Commercial-Service/conclave-ssso-ui#837
=> Revert "3046 issues fixed (#836)"

src/app/pages/manage-organisation/manage-organisation-profile/manage-organisation-profile.component.html, src/app/pages/user-profile/user-profile-component.html, src/app/services/wrapper/wrapper-configuration.service.ts
* idps hide manage org and manage user
* did a changes in org and user pages
=> Hide idps in sprint13 branch (#855)

src/app/pages/buyer/confirm-org-type/confirm-org-type.component.html, src/app/pages/buyer/update-org-type/update-org-type.component.html, src/app/pages/buyer/update-org-type/update-org-type.component.scss, src/app/pages/buyer/update-org-type/update-org-type.component.ts
* 4016-bugs-fixed
* auto validation success part updated
* typo changes
=> 4016 mse bugs (#877)

src/app/components/govuk-table/govuk-table.component.html, src/app/components/govuk-table/govuk-table.component.ts, src/app/pages/buyer/auto-validation-buyer-success/auto-validation-buyer-success.component.html, src/app/pages/buyer/auto-validation-buyer-success/auto-validation-buyer-success.component.ts, src/app/pages/buyer/confirm-changes/confirm.component.ts, src/app/pages/buyer/update-org-type/update-org-type.component.ts, src/app/pages/manage-buyer-and-both-requests/remove-right-to-buy/remove-right-to-buy.component.ts, src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.html, src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.ts, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.html, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.ts
* #
* table issue fixed
* fixed four bugs
=> Auto validation ajith (#890)

src/app/components/govuk-table/govuk-table.component.ts, src/app/pages/buyer/auto-validation-buyer-success/auto-validation-buyer-success.component.ts, src/app/pages/buyer/update-org-type/update-org-type.component.ts
* auto validation pending bug fixed
* 4039 issues fixed
* #
* #
* #
=> 4039 confirmation page issue mse (#895)

src/app/pages/buyer/confirm-org-type/confirm-org-type.component.ts
[Bug 4069](https://dev.azure.com/CCS-Conclave/CCS-Conclave-P2/_workitems/edit/4069): Issue with removing roles when changing organisation type from supplier to buyer or both in auto validation fail scenario and manually accepting the validation
=> Bug 4069: UI

e2e/tsconfig.json, tsconfig.app.json, tsconfig.json, tsconfig.spec.json, tsconfig.worker.json
comments from json files are removed
=> PR-json-fix-Snky-Import-exceptions-UI

src/app/pages/buyer/auto-validation-buyer-success/auto-validation-buyer-success.component.html, src/app/pages/buyer/confirm-changes/confirm.component.html, src/app/pages/buyer/confirm-org-type/confirm-org-type.component.html, src/app/pages/buyer/confirm/confirm.component.html, src/app/pages/buyer/update-org-type/update-org-type.component.html, src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.ts, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.ts, src/app/pages/manage-delegated/delegated-access-user/delegated-access-user.component.html, src/app/pages/manage-delegated/delegated-user-confirm/delegated-user-confirm.component.html, src/app/pages/user-profile/user-profile-component.ts, src/app/services/wrapper/wrapper-org--group-service.ts
=> Role rename changes

src/app/pages/buyer/update-org-type/update-org-type.component.ts
* 4156 issue fixed and did buddy check with kawshi
* typo correction fixed as per review
=> 4156 issue fixed and did buddy check with kawshi (#934)

src/app/pages/contact-admin/contact-admin.component.html, src/app/pages/contact-admin/contact-admin.component.ts, src/app/pages/home/home.component.html, src/app/pages/home/home.component.ts, src/app/pages/operation-success/operation-success.component.html, src/app/pages/operation-success/operation-success.component.ts, src/app/pages/user-contact/user-contact-delete-confirm/user-contact-delete-confirm-component.html, src/app/pages/user-contact/user-contact-delete-confirm/user-contact-delete-confirm-component.ts, src/app/pages/user-contact/user-contact-edit/user-contact-edit.component.html, src/app/pages/user-contact/user-contact-edit/user-contact-edit.component.ts, src/app/pages/user-profile-mfa/confirm-mfa-reset/confirm-mfa-reset.component.html, src/app/pages/user-profile-mfa/confirm-mfa-reset/confirm-mfa-reset.component.ts, src/app/pages/user-profile-mfa/success-user-mfa/success-user-mfa.component.html, src/app/pages/user-profile-mfa/success-user-mfa/success-user-mfa.component.ts, src/app/pages/user-profile/user-profile-component.html, src/assets/i18n/en.json
=> Release:Sandbox release note-20221213-(Phase 3 Sprint 1)

src/app/pages/buyer/update-org-type/update-org-type.component.ts, src/app/pages/user-profile/user-profile-component.html, src/app/pages/user-profile/user-profile-component.scss
* 3065-table-implement complete
* 4156 issue fixed and did buddy check with kawshi (#934)
* 4156 issue fixed and did buddy check with kawshi
* typo correction fixed as per review
* 4085 issue 2 fixed (#938)
* table updated manage account
=> Release: Sandbox_release_note-20221214-1

src/app/pages/user-profile/user-profile-component.html, src/app/pages/user-profile/user-profile-component.ts
…org users (#944)
* Task 4154: CON-2405 - Incorrect 'Administrator' dashboard labels for org users
* Task 4154: CON-2405 - Incorrect 'Administrator' dashboard labels for org users
=> Release: Bug 4173 & Task 4154- Fixes on sandbox

src/app/pages/manage-user/manage-user-confirm-reset-password/manage-user-confirm-reset-password-component.ts, src/app/pages/manage-user/manage-user-delete-confirm/manage-user-delete-confirm-component.ts
[Bug 4207](https://dev.azure.com/CCS-Conclave/CCS-Conclave_P3/_workitems/edit/4207): Blank page is displaying when Click on Cancel button from Delete user
=> Bug 4207: Blank page is displaying when Click on Cancel button from Delete user

Auth0Templates/Mfa.html, src/app/pages/forgot-password-success/forgot-password-success.html, src/app/pages/manage-organisation/manage-organisation-registration-add-user/manage-organisation-registration-add-user.component.html, src/app/pages/manage-organisation/manage-organisation-registration-add-user/manage-organisation-registration-add-user.component.ts, src/app/pages/manage-organisation/manage-organisation-registration-confirm/manage-organisation-registration-confirm.component.ts, src/app/pages/manage-organisation/manage-organisation-registration-step-2/manage-organisation-registration-step-2.component.ts, src/app/pages/manage-organisation/manage-reg-organisation-admin-notify/manage-reg-organisation-admin-notify.component.html, src/app/pages/manage-organisation/manage-reg-organisation-admin-notify/manage-reg-organisation-admin-notify.component.ts, src/app/pages/manage-organisation/manage-reg-organisation-not-registered/manage-reg-organisation-not-registered.component.ts, src/app/pages/manage-organisation/manage-reg-organisation-search/manage-reg-organisation-search.component.ts, src/app/pages/manage-organisation/manage-reg-organisation-status-duplicate/manage-reg-organisation-status-duplicate.component.html, src/app/pages/manage-organisation/manage-reg-organisation-status-exists/manage-reg-organisation-status-exists.component.html, src/app/pages/manage-organisation/manage-reg-organisation-status-exists/manage-reg-organisation-status-exists.component.ts, src/app/pages/nominate-success/nominate-success.component.html, src/app/pages/nominate-success/nominate-success.component.ts, src/app/pages/nominate/nominate.component.html, src/app/pages/nominate/nominate.component.ts, src/assets/i18n/en.json, src/styles.scss
* 4212 bug observations fixed
* css formated
=> 4211 add breadcrumbs bugs (#959)

src/app/app-routing.module.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/models/organisationGroup.ts, src/app/models/user.ts, src/app/pages/auth-success/auth-success.component.ts, src/app/pages/manage-role/manage-user-role/manage-user-role.component.html, src/app/pages/manage-role/manage-user-role/manage-user-role.component.scss, src/app/pages/manage-role/manage-user-role/manage-user-role.component.spec.ts, src/app/pages/manage-role/manage-user-role/manage-user-role.component.ts, src/app/pages/manage-role/role-request-failed/role-request-failed.component.html, src/app/pages/manage-role/role-request-failed/role-request-failed.component.spec.ts, src/app/pages/manage-role/role-request-failed/role-request-failed.component.ts, src/app/pages/manage-role/role-request-success/role-request-success.component.html, src/app/pages/manage-role/role-request-success/role-request-success.component.scss, src/app/pages/manage-role/role-request-success/role-request-success.component.spec.ts, src/app/pages/manage-role/role-request-success/role-request-success.component.ts, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.html, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/app/pages/operation-success/operation-success.component.html, src/app/pages/operation-success/operation-success.component.ts, src/app/pages/user-profile/user-profile-component.html, src/app/pages/user-profile/user-profile-component.ts, src/app/services/auth/auth.service.ts, src/app/services/wrapper/wrapper-org--group-service.ts, src/app/services/wrapper/wrapper-user.service.ts
* 2893-api call updated
* 2893-re-direct-link-updated
* daily update
* post and put call updated
* create user flow complete
* approve and reject flow
* manage my account complete
* commited
=> Con 2893 fleet portal UI (#999)

src/app/models/organisation.ts, src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.html, src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.ts, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.html, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.ts, src/app/pages/manage-role/role-request-failed/role-request-failed.component.html, src/app/pages/operation-success/operation-success.component.html
* 3358 and 4388 completed did a buddy check with Leela
* updated
=> Con 3358 auto validation bug UI (#1003)

src/app/pages/user-profile/user-profile-component.ts
manage my account page when
fleet portal  role is selected when
domain names are same
=> CON-4393-frontend fix applied to fix the (#1008)

src/app/pages/manage-organisation/manage-organisation-profile-registry-search/manage-organisation-profile-registry-search.component.html, src/app/pages/manage-organisation/manage-organisation-registration-step-1/manage-organisation-registration-step-1.component.html, src/app/pages/manage-organisation/manage-organisation-registration-step-2/manage-organisation-registration-step-2.component.html
School registry UI Changes are done. Need to test it in DEV environment.
=> PR-4408-Con-3359-CII-Integration-School-registry---UI-changes-Priority-1

src/app/pages/manage-organisation/manage-organisation-profile-registry-search/manage-organisation-profile-registry-search.component.html, src/app/pages/manage-organisation/manage-organisation-registration-step-1/manage-organisation-registration-step-1.component.html, src/app/pages/manage-organisation/manage-organisation-registration-step-2/manage-organisation-registration-step-2.component.html
Need to test it in DEV environment.
=> School registry UI Changes are done. (#1049)

src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.ts, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.ts
* Event log show service name with role name
* Code review changes
* Code review change
=> Event log show service name with role name (#1059)

src/app/components/govuk-table/govuk-table.component.html, src/app/components/govuk-table/govuk-table.component.scss, src/app/models/organisationGroup.ts, src/app/pages/home/home.component.ts, src/app/pages/manage-delegated/service/manage-delegate.service.ts, src/app/pages/manage-delegated/user/delegated-organisation/delegated-organisation.component.ts, src/app/pages/manage-group/manage-group-edit-roles/manage-group-edit-roles-component.ts
* testing for json scheema
* dev kit removal fix
* 3449 ,4502 and 4503 issue are fixed
* package file updated
* lock file updated
=> 3449 manage group changes (#1064)

src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/app/pages/manage-user/manage-user-profiles/manage-user-profiles-component.ts, src/app/services/auth/auth.service.ts, src/app/shared/shared-data.service.ts
This reverts commit 04bf4d2a7562a04dcfa2c9c8fd915d6fb3b61110.
=> Revert "4509 issue fixes (#1071)"

src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/app/pages/manage-user/manage-user-profiles/manage-user-profiles-component.ts, src/app/services/auth/auth.service.ts, src/app/shared/shared-data.service.ts
* 4509 issue fixes
* commit error fixes
=> 4509 issue with loading the edit use (#1074)

src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts
[Bug 4402](https://dev.azure.com/CCS-Conclave/CCS-Conclave_P3/_workitems/edit/4402): Sprint 4-:User update issues with approval required multiple roles
=> Multiple approval role save button not working

src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/app/pages/user-profile/user-profile-component.ts
[Bug 4398](https://dev.azure.com/CCS-Conclave/CCS-Conclave_P3/_workitems/edit/4398): Sprint 4-:Issues in POST {{apigwurl}}/user-profiles/approve/roles API
=> Bug 4398: Sprint 4-:Issues in POST {{apigwurl}}/user-profiles/approve/roles API

src/app/pages/manage-buyer-and-both-requests/confirm-decline/confirm-decline.component.html, src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.html, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.html
con 3379 auto validation  non functional issues
=> PR-CON-3379-Auto-validation--non-functional-issues

src/app/pages/manage-organisation/manage-organisation-profile-registry-search/manage-organisation-profile-registry-search.component.html, src/app/pages/manage-organisation/manage-organisation-registration-step-2/manage-organisation-registration-step-2.component.html
* error msg content changed
* msg updated
=> Con 3593 error text change UI (#1114)

Auth0Templates/Mfa.html, src/app/pages/manage-group/manage-group-edit-users/manage-group-edit-users-component.html, src/app/pages/manage-group/manage-group-edit-users/manage-group-edit-users-component.ts, src/app/pages/manage-group/manage-group-error/manage-group-error.component.html, src/app/pages/manage-group/manage-group-error/manage-group-error.component.ts, src/app/pages/manage-group/manage-group-list/manage-group-list-component.html, src/app/pages/manage-group/manage-group-list/manage-group-list-component.ts, src/app/pages/manage-role/role-request-success/role-request-success.component.html, src/app/pages/manage-role/role-request-success/role-request-success.component.ts, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/app/pages/operation-success/operation-success.component.html, src/app/pages/operation-success/operation-success.component.ts, src/app/pages/user-profile/user-profile-component.ts, src/app/services/wrapper/wrapper-org--group-service.ts, src/app/services/wrapper/wrapper-user.service.ts
* fleet api integration and mfa page changes
* fleet table removed
=> fleet api integration and mfa page changes (#1156)

src/app/pages/operation-success/operation-success.component.ts
* contion added
* condtion changes
=> 2287 user success page not working (#1162)

src/app/pages/home/home.component.ts, src/app/pages/operation-success/operation-success.component.html
=> 4920 dashboard issue (#1187)

src/app/pages/user-profile/user-profile-component.ts
* issue fixed
* debugger removed
=> issue fixed (#1204)

src/app/pages/manage-delegated/delegated-access-user/delegated-access-user.component.ts
[Bug 5003](https://dev.azure.com/CCS-Conclave/CCS-Conclave_P3/_workitems/edit/5003): Data Migration service is not exclude from delegation
=> Bug 5003: Data Migration service is not exclude from delegation

src/app/pages/user-profile/user-profile-component.ts
[Bug 5000](https://dev.azure.com/CCS-Conclave/CCS-Conclave_P3/_workitems/edit/5000): PPG -213 - Org user - Manage my account - On clicking 'Save changes.' - no response and no error observed in console and network tab
=> Bug 5000 fix for p3sprint6 on test env

src/app/models/organisationGroup.ts, src/app/pages/manage-group/manage-group-edit-name/manage-group-edit-name-component.ts, src/app/pages/manage-group/manage-group-edit-roles-confirm/manage-group-edit-roles-confirm-component.ts, src/app/pages/manage-group/manage-group-edit-roles/manage-group-edit-roles-component.html, src/app/pages/manage-group/manage-group-edit-roles/manage-group-edit-roles-component.ts, src/app/pages/manage-group/manage-group-operation-success/manage-group-operation-success-component.html, src/app/pages/manage-group/manage-group-operation-success/manage-group-operation-success-component.scss, src/app/pages/manage-group/manage-group-operation-success/manage-group-operation-success-component.ts, src/app/pages/manage-group/manage-group-view/manage-group-view-component.ts, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/app/pages/operation-success/operation-success.component.html, src/app/pages/operation-success/operation-success.component.ts, src/app/pages/user-profile/user-profile-component.ts, src/app/services/auth/auth.service.ts, src/app/services/wrapper/wrapper-org--group-service.ts
* accordino and mock api integration complete
* disbale condition removed
* 212 ui work completed
=> PPG 212 non associated email domain check UI (#1222)

src/app/pages/buyer/details/details.component.ts, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.ts
Task 5421: PPON -PPG 59/60-Dev -UI Changes for p3s9
=> Task 5421: PPON -PPG 59/60-Dev -UI Changes for p3s9

src/app/pages/buyer/details/details.component.html, src/app/pages/buyer/details/details.component.ts, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.html, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.ts
* Task 5421: PPON -PPG 59/60-Dev -UI Changes for p3s9
* Task 5421: PPON -PPG 59/60-Dev -UI Changes
=> Task 5421: PPON -PPG 59/60-Dev -UI Changes (#1269)

src/app/app.module.ts, src/app/components/accordion/accordion.component.html, src/app/components/accordion/accordion.component.scss, src/app/components/accordion/accordion.component.spec.ts, src/app/components/accordion/accordion.component.ts, src/app/components/govuk-table/govuk-table.component.html, src/app/models/organisationGroup.ts, src/app/models/user.ts, src/app/pages/manage-group/manage-group-edit-users/manage-group-edit-users-component.ts, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.html, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.scss, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/app/pages/manage-user/verify-user-status/verify-user-status.component.html, src/app/pages/user-profile/user-profile-component.html, src/app/pages/user-profile/user-profile-component.scss, src/app/pages/user-profile/user-profile-component.ts, src/app/services/wrapper/wrapper-org--group-service.ts, src/app/services/wrapper/wrapper-user.service.ts, src/assets/i18n/en.json
* common component creation completed
* org user view complete (#1250)
* juki work added (#1253)
* Ppg 40 manage user api inegration (#1254)
* juki work added
* role pending status functionlity done
* Approval status changes
* Group - Save button enable
* Task 5412: PPG-40 - The Manage Groups functionality Changes - service tab creation (#1261)
* Feature/ppg 40 vijay the manage groups functionality changes UI (#1262)
* Group related changes are done for manage my account page
* normal users A/Cs are verified and fixed.
* govuk table pending label implementation
* Feature/ppg 40 vijay the manage groups functionality changes UI (#1272)
* Group related changes are done for manage my account page
* normal users A/Cs are verified and fixed.
* can see all the group services
* Ppg 40 tab group …
=> Ppg 40 the manage groups functionality changes UI (#1274)

src/app/pages/buyer/details/details.component.ts, src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.html, src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.ts, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.ts
* Task 5421: PPON -PPG 59/60-Dev -UI Changes for p3s9
* Task 5421: PPON -PPG 59/60-Dev -UI Changes
* Task 5421: PPON -PPG 59/60-Dev -UI Changes
=> Task 5421: PPON -PPG 59/60-Dev -UI Changes (#1284)

src/app/pages/buyer/details/details.component.html, src/app/pages/buyer/details/details.component.ts, src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.html, src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.ts, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.html, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.ts, src/app/pages/manage-organisation/manage-organisation-profile-registry-search/manage-organisation-profile-registry-search.component.html, src/app/pages/manage-organisation/manage-organisation-profile-registry-search/manage-organisation-profile-registry-search.component.scss, src/app/pages/manage-organisation/manage-organisation-profile-registry-search/manage-organisation-profile-registry-search.component.ts, src/app/pages/manage-organisation/manage-organisation-profile/manage-organisation-profile.component.ts, src/app/pages/manage-organisation/manage-organisation-registration-step-1/manage-organisation-registration-step-1.component.html, src/app/pages/manage-organisation/manage-organisation-registration-step-1/manage-organisation-registration-step-1.component.ts, src/app/pages/manage-organisation/manage-organisation-registration-step-2/manage-organisation-registration-step-2.component.html, src/app/pages/manage-organisation/manage-organisation-registration-step-2/manage-organisation-registration-step-2.component.scss, src/app/pages/manage-organisation/manage-organisation-registration-step-2/manage-organisation-registration-step-2.component.ts, src/app/shared/shared-data.service.ts, src/environments/environment.ts
=> PPON UI changes for p3sprint8

src/app/pages/buyer/details/details.component.html, src/app/pages/buyer/details/details.component.ts, src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.html, src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.ts, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.html, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.ts, src/app/pages/manage-organisation/manage-organisation-profile-registry-search/manage-organisation-profile-registry-search.component.html, src/app/pages/manage-organisation/manage-organisation-profile-registry-search/manage-organisation-profile-registry-search.component.scss, src/app/pages/manage-organisation/manage-organisation-profile-registry-search/manage-organisation-profile-registry-search.component.ts, src/app/pages/manage-organisation/manage-organisation-profile/manage-organisation-profile.component.ts, src/app/pages/manage-organisation/manage-organisation-registration-step-1/manage-organisation-registration-step-1.component.html, src/app/pages/manage-organisation/manage-organisation-registration-step-1/manage-organisation-registration-step-1.component.ts, src/app/pages/manage-organisation/manage-organisation-registration-step-2/manage-organisation-registration-step-2.component.html, src/app/pages/manage-organisation/manage-organisation-registration-step-2/manage-organisation-registration-step-2.component.scss, src/app/pages/manage-organisation/manage-organisation-registration-step-2/manage-organisation-registration-step-2.component.ts, src/app/shared/shared-data.service.ts, src/environments/environment.ts
* PPON UI changes for s8
* Task 5421: PPON -PPG 59/60-Dev -UI Changes
* changes are done
---------
=> PPON UI changes for p3sprint8 (#1271) to Testing on Apr27,2023

.github/codeclimate.yml, .github/workflows/monthly-scan.yml, src/app/components/custom-govuk-table/custom-govuk-table.component.html, src/app/components/custom-govuk-table/custom-govuk-table.component.ts, src/app/components/govuk-table/govuk-table.component.ts, src/app/pages/buyer/details/details.component.ts, src/app/pages/data-migration/data-migration-error/data-migration-error.component.ts, src/app/pages/manage-buyer-and-both-requests/view-pending-verification/view-pending-verification.component.ts, src/app/pages/manage-buyer-and-both-requests/view-verified-org/view-verified-org.component.ts, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/app/pages/user-profile/user-profile-component.ts, src/app/shared/shared-data.service.ts, src/environments/environment-testing.ts
* Update environment-testing.ts
* Update .travis.yml
* #
* update nodejs version
* Update environment-testing.ts
* Bug 5000 fix for p3sprint6 on test env (#1212)
* table coumn issue fixed (#1234)
* sprint 7 changes done(hot fix) (#1236)
* fixed in sprint8 and 9 (#1247)
* issue fixed in p3sprin7 (#1248)
* Bug 5474: PPG 170 - User not Created - Text change from 'You do not have permission to action this request' to 'You don’t have permission to action this request' (#1255)
* Bug 5474: PPG 170 - User not Created - Text change from 'You do not have permission to action this request' to 'You don’t have permission to action this request' (#1256)
* codeclimate encryptions added
* release tags added
* release tags added
* release tags added
* tag added
* tag
* tag
* release.sh
* release tag added …
=> Code climate issue p3sprin9 (#1311)

src/app/pages/home/home.component.ts, src/app/pages/manage-group/manage-group-view/manage-group-view-component.html, src/app/pages/manage-group/manage-group-view/manage-group-view-component.ts
* Fixed Data Migrations bugs 5556, 5558, 5555, 5553
* Data migration bug fixed.
* Data migration bug: Removed one condition
* Fixed bugs 5607 and 5608
=> Fixed Bugs 5607 and 5608 (#1313)

src/app/components/custom-govuk-table/custom-govuk-table.component.html, src/app/pages/data-migration/data-migration-upload/data-migration-upload.component.html, src/app/pages/data-migration/data-migration-upload/data-migration-upload.component.scss, src/app/pages/data-migration/data-migration-upload/data-migration-upload.component.ts
* Fixed Data Migrations bugs 5556, 5558, 5555, 5553
* Data migration bug fixed.
* Data migration bug: Removed one condition
* Fixed bugs 5607 and 5608
* Fixed Bug Bug 5627: UI Issues with Data Migration
=> Fixed bug 5627 Accessibility UI Issues with Data Migration (#1315)

src/app/app.module.ts, src/app/components/govuk-radio/govuk-radio.component.html, src/app/components/govuk-radio/govuk-radio.component.scss, src/app/components/govuk-radio/govuk-radio.component.spec.ts, src/app/components/govuk-radio/govuk-radio.component.ts, src/app/models/user.ts, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.html, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/app/pages/user-profile/user-profile-component.html, src/app/pages/user-profile/user-profile-component.scss, src/app/pages/user-profile/user-profile-component.ts
* common component functionlity is completed
* Task 5595: PPG-257 - User type selector - Brijesh's task
* Task 5595: PPG-257 - User type selector - profile changes
* User type implementation for manage users
* Task 5595: PPG-257 - User type selector - Brijesh's task
* Task 5595: PPG-257 - User type selector - Brijesh's task
---------
=> PPG 257 UI changes (#1340)

src/app/pages/manage-organisation/manage-organisation-contact-edit/manage-organisation-contact-edit.component.html
* Task 5597: PPG-41 - Error validation UI issues (red line next to fields)
* Modified-toolkit.css
* Updated-toolkit.css
* ChangesUpdated-PPG-41
---------
=> Feature/ppg 41 task 5597 errorvalidation (#1346)

src/app/components/business/reg-org-details/reg-org-details.component.html, src/app/pages/manage-organisation/manage-organisation-registration-add-user/manage-organisation-registration-add-user.component.html, src/app/pages/manage-organisation/manage-organisation-registration-step-1/manage-organisation-registration-step-1.component.html, src/app/pages/manage-organisation/manage-organisation-registration-step-3/manage-organisation-registration-step-3.component.html, src/app/pages/manage-organisation/manage-reg-organisation-search/manage-reg-organisation-search.component.html, src/app/pages/manage-organisation/manage-reg-organisation-status-exists/manage-reg-organisation-status-exists.component.html
* 5666-registration UI Changes are made
* updated after QA check
* Few text and typo  are corrected
=> Feature/5666 ppg 267 update registration screens content (#1395)

src/app/components/accordion/accordion.component.html, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/app/pages/user-profile/user-profile-component.ts
* daily updates
* task complete
* #
=> daily updates (#1434)

src/app/components/accordion/accordion.component.html, src/app/components/govuk-table/govuk-table.component.ts, src/app/models/user.ts, src/app/pages/manage-group/manage-group-edit-users/manage-group-edit-users-component.ts, src/app/pages/manage-group/manage-group-view/manage-group-view-component.html
* manage group changes are done
* #
=> 5767 add contextual into the admin group (#1441)

.github/workflows/monthly-scan.yml, .github/workflows/secrets-scan.yml
Reverts Crown-Commercial-Service/conclave-ssso-ui#1452
=> Revert "p3sprint13 Branch has been created 13.06.2023"

src/app/components/accordion/accordion.component.html, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts
* p3sprint12 changes are done
* 6116 and 6117 task has been completed
=> Hide show all in manage user UI (#1467)

src/app/components/accordion/accordion.component.html, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts
* group type issue fixed
* two issue has been fixed
=> 6081 group type issue p3sprint12 (#1475)

src/app/interceptors/loading-indicator.interceptor.ts, src/app/pages/buyer/confirm-org-service/confirm-org-service.component.ts, src/app/pages/buyer/confirm-org-type/confirm-org-type.component.ts, src/app/services/auth/auth.service.ts, src/app/services/auth/mfa.service.ts, src/app/services/postgres/bulk-upload.service.ts, src/app/services/postgres/data-migration.service.ts, src/app/services/postgres/organisation.service.ts, src/app/services/wrapper/wrapper-buyer-both.service.ts, src/app/services/wrapper/wrapper-configuration.service.ts, src/app/services/wrapper/wrapper-org--group-service.ts, src/app/services/wrapper/wrapper-org-contact-service.ts, src/app/services/wrapper/wrapper-org-service.ts, src/app/services/wrapper/wrapper-site-contact-service.ts, src/app/services/wrapper/wrapper-user-delegated.service.ts, src/app/services/wrapper/wrapper-user.service.ts, src/environments/environment-NFT.ts, src/environments/environment-development.ts, src/environments/environment-pre-production.ts, src/environments/environment-production.ts, src/environments/environment-sandbox.ts, src/environments/environment-testing.ts, src/environments/environment-uat.ts, src/environments/environment.ts
* changes are done for micro service
* auth changes are done
* Update environment-uat.ts
* Update environment-testing.ts
* Update environment-development.ts
* Update environment-pre-production.ts
* Update environment-production.ts
* Update environment-sandbox.ts
* Update environment-NFT.ts
* Update environment-development.ts
* Update environment-development.ts
=> changes are done for micro service (#1563)

Auth0Templates/ResetPassword.html, src/app/pages/change-password/change-password.component.ts
https://dev.azure.com/CCS-Conclave/CCS-Conclave_P3/_workitems/edit/6603
=> Task 6603: PPG-576 | Update password rules content

src/index.html
Reverts Crown-Commercial-Service/conclave-ssso-ui#1746
=> Revert "csp issue updated"

src/app/pages/contact-admin/contact-admin.component.ts, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.html, src/app/pages/two-mfa/mfa-authenticator/mfa-authenticator-information/mfa-authenticator-information.component.html, src/app/pages/two-mfa/mfa-authenticator/mfa-authenticator-information/mfa-authenticator-information.component.scss, src/app/pages/two-mfa/mfa-authenticator/mfa-authenticator-setup/mfa-authenticator-setup.component.html, src/app/pages/two-mfa/mfa-authenticator/mfa-authenticator-setup/mfa-authenticator-setup.component.scss, src/app/pages/two-mfa/mfa-authenticator/mfa-authenticator-setup/mfa-authenticator-setup.component.ts, src/app/pages/two-mfa/mfa-message/mfa-message-step-1/mfa-message-step-1.component.html, src/app/pages/two-mfa/mfa-message/mfa-message-step-1/mfa-message-step-1.component.scss, src/app/pages/two-mfa/mfa-message/mfa-message-step-2/mfa-message-step-2.component.html, src/app/pages/two-mfa/mfa-message/mfa-message-step-2/mfa-message-step-2.component.ts, src/app/pages/user-profile/user-profile-component.html, src/app/pages/user-profile/user-profile-component.ts
* Bug-6934,6932 Fixed MFA bugs and also minor UI issues
* Fixed duplicate mfopted value passing in the payload of update user
=> Bug-6934,6932 Fixed MFA bugs and also minor UI issues (#1779)

src/app/pages/manage-delegated/delegated-user-list/delegated-user-list.component.ts
Bug 6909: Force Logout - User navigates to error page than navigated to sign in page, only when the next action is 'Clicking Delegated Access.'
=> Bug 6909: Force Logout - User navigates to error page

src/app/app.component.ts
while login and lands on a new MFA page
=> Bug 7087: PPG 848 - The page redirects several times or flickers

src/app/app.component.ts, src/app/services/auth/auth.service.ts
while login and lands on a new MFA page
=> Bug 7087: PPG 848 - The page redirects several times or flickers 

src/assets/rpIFrame.js
Reverts Crown-Commercial-Service/conclave-ssso-ui#1963
=> Revert "Task 6916: PPG-801 - Issues with relying party[CAS] session timeout a…"

src/app/pages/manage-organisation/manage-organisation-profile-add-contact-to-site/manage-organisation-profile-add-contact-to-site.component.html
* fixed bug 7205 hidden delete site link
* fixed bug 7207 No response when clicking cancel
=> Bug/7205 disable delete site link (#1983)

src/app/components/accordion/accordion.component.html, src/app/pages/manage-organisation/manage-organisation-profile-site-edit/manage-organisation-profile-site-edit.component.html, src/app/pages/manage-organisation/manage-organisation-profile-site-edit/manage-organisation-profile-site-edit.component.scss, src/app/pages/manage-organisation/manage-organisation-registration-step-3/manage-organisation-registration-step-3.component.html, src/app/pages/manage-organisation/manage-organisation-registration-step-3/manage-organisation-registration-step-3.component.scss, src/app/pages/manage-organisation/manage-reg-organisation-search/manage-reg-organisation-search.component.html, src/app/pages/manage-organisation/manage-reg-organisation-search/manage-reg-organisation-search.component.scss, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.html, src/app/pages/manage-user/manage-user-add-single-user-detail/manage-user-add-single-user-detail.component.ts, src/styles.scss
* Upgraded angular from 14 to 15
* Update angular material version from 11 to 12
* Upgaded angular material version from 12 to 13.
* Upgraded angular material from 13 to 14
* Upgraded angular material version from 14 to 15
* updated angular version from 15 to 16 with other packages. changes made in auth guard.
* FIxed Bugs related to angular version upgrade related to 16
=> Fixed bugs related to angular version 16 upgrade (#2224)

src/app/components/terms-conditions/terms-conditions.component.scss
* Upgraded angular from 14 to 15
* Update angular material version from 11 to 12
* Upgaded angular material version from 12 to 13.
* Upgraded angular material from 13 to 14
* Upgraded angular material version from 14 to 15
* updated angular version from 15 to 16 with other packages. changes made in auth guard.
* FIxed Bugs related to angular version upgrade related to 16
* Fixed accessibility issue in Terms and Use page
=> Feature/angular upgrade 14 to 15 (#2227)

src/app/pages/manage-organisation/manage-organisation-profile-site-edit/manage-organisation-profile-site-edit.component.scss, src/app/pages/manage-organisation/manage-organisation-registration-step-3/manage-organisation-registration-step-3.component.scss, src/app/pages/manage-organisation/manage-reg-organisation-search/manage-reg-organisation-search.component.scss
* Angular upgrade from 16 to 17.
* Angular 17 upgrade bug fixes.
=> angular 17 upgrade bug fixes (#2248)
